export const categories = [
  {
    id: 'ceramics',
    label: 'Ceramics',
    subtitle: 'Handcrafted with intention',
    desc: 'Each piece is thrown or hand-built by skilled artisans, fired to perfection, and finished with our signature earth-toned glazes.',
    tag: 'Artisan Made',
    image: '/images/hero-ceramics.png',
    lightBg: '#F5EEE6',
    overlayColor: 'rgba(139,115,85,0.55)',
  },
  {
    id: 'textiles',
    label: 'Textiles',
    subtitle: 'Woven with care',
    desc: 'From linen throws to merino cushions, our textile collection brings warmth and texture to every room in your home.',
    tag: 'Natural Fibres',
    image: '/images/hero-textiles.png',
    lightBg: '#FBF5EA',
    overlayColor: 'rgba(200,169,110,0.55)',
  },
  {
    id: 'decor',
    label: 'Decor',
    subtitle: 'Details that matter',
    desc: 'Thoughtfully designed objects that bring beauty and function together. Each piece is chosen to complement your living space.',
    tag: 'Limited Edition',
    image: '/images/hero-decor.png',
    lightBg: '#F5F0EA',
    overlayColor: 'rgba(176,160,144,0.55)',
  },
  {
    id: 'furniture',
    label: 'Furniture',
    subtitle: 'Built to last generations',
    desc: 'Solid wood and premium materials crafted into pieces that anchor your home with warmth and timeless character.',
    tag: 'Solid Wood',
    image: '/images/hero-furniture.png',
    lightBg: '#F0EBE3',
    overlayColor: 'rgba(120,95,75,0.55)',
  },
  {
    id: 'lighting',
    label: 'Lighting',
    subtitle: 'Set the perfect mood',
    desc: 'From pendant lights to table lamps, our lighting collection transforms any space with warmth and atmosphere.',
    tag: 'Handmade',
    image: '/images/hero-lighting.png',
    lightBg: '#FDF8EE',
    overlayColor: 'rgba(180,155,90,0.55)',
  },
  {
    id: 'garden',
    label: 'Garden & Outdoor',
    subtitle: 'Bring beauty outdoors',
    desc: 'Planters, tools, and outdoor accessories designed to make your garden and balcony as beautiful as your home.',
    tag: 'Outdoor Living',
    image: '/images/hero-garden.png',
    lightBg: '#EEF4EE',
    overlayColor: 'rgba(80,110,80,0.55)',
  },
  {
    id: 'bath',
    label: 'Bath & Wellness',
    subtitle: 'Your daily ritual, elevated',
    desc: 'Luxurious towels, bath accessories, and wellness products that turn your bathroom into a personal sanctuary.',
    tag: 'Self Care',
    image: '/images/hero-bath.png',
    lightBg: '#EEF2F5',
    overlayColor: 'rgba(100,130,150,0.55)',
  },
  {
    id: 'storage',
    label: 'Storage & Organisation',
    subtitle: 'Beautiful order',
    desc: 'Baskets, boxes, and shelving that bring calm and order to your home without sacrificing style.',
    tag: 'Functional Design',
    image: '/images/hero-storage.png',
    lightBg: '#F2EEE8',
    overlayColor: 'rgba(140,120,100,0.55)',
  },
]

export const getCategoryById = (id) => categories.find(c => c.id === id)
export const categoryIds = ['all', ...categories.map(c => c.id)]
export const categoryLabels = { all: 'All', ...Object.fromEntries(categories.map(c => [c.id, c.label])) }
