export const products = [
  {
    id: 1,
    name: 'Stoneware Mug Set',
    category: 'ceramics',
    price: 48,
    oldPrice: null,
    emoji: '☕',
    badge: 'new',
    bg: '#F0EAE0',
    description: 'Handcrafted stoneware mugs with a natural matte glaze. Each set includes 2 mugs in complementary earth tones. Microwave and dishwasher safe.',
    details: ['Set of 2 mugs', '350ml capacity each', 'Matte stoneware glaze', 'Dishwasher safe', 'Made in Portugal'],
    rating: 4.9,
    reviews: 142,
  },
  {
    id: 2,
    name: 'Linen Throw Blanket',
    category: 'textiles',
    price: 120,
    oldPrice: 160,
    emoji: '🧶',
    badge: 'sale',
    bg: '#EDE8E0',
    description: 'A luxuriously soft linen-cotton blend throw. Pre-washed for an instantly relaxed feel. Perfect for layering on beds or draped over sofas.',
    details: ['130 × 170 cm', '55% linen, 45% cotton', 'Pre-washed for softness', 'Machine washable', 'Available in 4 colours'],
    rating: 4.8,
    reviews: 89,
  },
  {
    id: 3,
    name: 'Ceramic Vase, Tall',
    category: 'ceramics',
    price: 75,
    oldPrice: null,
    emoji: '🏺',
    badge: null,
    bg: '#E8E0D5',
    description: 'A statement piece for any room. This tall ceramic vase features a subtly textured surface and a warm terracotta-toned glaze that catches the light beautifully.',
    details: ['Height: 32cm', 'Opening diameter: 8cm', 'Terracotta glaze', 'Waterproof interior', 'Handmade'],
    rating: 4.7,
    reviews: 56,
  },
  {
    id: 4,
    name: 'Beeswax Candle Trio',
    category: 'decor',
    price: 38,
    oldPrice: null,
    emoji: '🕯️',
    badge: 'new',
    bg: '#F5EED8',
    description: 'Three pure beeswax pillar candles in graduating heights. Natural honey scent, slow-burning, and completely soot-free. A warm glow for any occasion.',
    details: ['Set of 3 candles', 'Heights: 10cm, 15cm, 20cm', '100% pure beeswax', '40+ hour burn time each', 'Natural honey scent'],
    rating: 4.9,
    reviews: 203,
  },
  {
    id: 5,
    name: 'Woven Table Runner',
    category: 'textiles',
    price: 55,
    oldPrice: null,
    emoji: '🪡',
    badge: null,
    bg: '#EDE5D8',
    description: 'Hand-woven by artisans in Oaxaca, this table runner adds texture and warmth to any dining table. Natural dyes give each piece subtle unique variations.',
    details: ['40 × 180 cm', '100% natural cotton', 'Hand-woven', 'Natural plant dyes', 'Spot clean recommended'],
    rating: 4.6,
    reviews: 34,
  },
  {
    id: 6,
    name: 'Terracotta Planter',
    category: 'ceramics',
    price: 42,
    oldPrice: null,
    emoji: '🪴',
    badge: null,
    bg: '#EAE0D0',
    description: 'A classic terracotta planter with a modern matte finish. Drainage hole included. Perfect for herbs, succulents, or trailing plants.',
    details: ['Diameter: 18cm', 'Height: 15cm', 'Drainage hole', 'Matte terracotta finish', 'Includes saucer'],
    rating: 4.8,
    reviews: 78,
  },
  {
    id: 7,
    name: 'Brass Candleholder',
    category: 'decor',
    price: 65,
    oldPrice: null,
    emoji: '✨',
    badge: 'new',
    bg: '#F2E8D0',
    description: 'A sculptural brass candleholder with an organic, hand-formed shape. Holds standard taper candles. The brushed brass finish develops a beautiful patina over time.',
    details: ['Height: 22cm', 'Solid brass', 'Brushed finish', 'Fits standard taper candles', 'Handcrafted'],
    rating: 4.9,
    reviews: 61,
  },
  {
    id: 8,
    name: 'Merino Cushion Cover',
    category: 'textiles',
    price: 88,
    oldPrice: 110,
    emoji: '🛋️',
    badge: 'sale',
    bg: '#E5DDD0',
    description: 'A supremely soft cushion cover in 100% extra-fine merino wool. Hidden zip closure. The ribbed texture adds subtle dimension without overpowering the room.',
    details: ['50 × 50 cm', '100% extra-fine merino', 'Hidden zip closure', 'Ribbed texture', 'Dry clean recommended'],
    rating: 4.7,
    reviews: 47,
  },
]

export const getProductById = (id) => products.find(p => p.id === Number(id))
export const getProductsByCategory = (cat) => cat === 'all' ? products : products.filter(p => p.category === cat)
export const categories = ['all', 'ceramics', 'textiles', 'decor']
